### PR TITLE
Changed fork to spawn for windows compatibility

### PR DESCRIPTION
**Pull request by skystebnicki**
We love using this plugin, but found it would not work on windows because Process.fork is not implemented on windows. This has been tested on both windows and OSX and is working well though. Would love to be able to install it with "vagrant plugin install vagrant-git"

### CODE REVIEW

**Comment by skystebnicki** [comment]
Is there any chance you might be up for merging this and publishing it? We wold love to deploy it to our windows users.

**Comment by alangarf** [comment]
Hi, let me test it and yes I'll publish a new release.

**Comment by alangarf** [comment]
Done! 0.1.7 released. Thanks!

@skystebnicki

**Comment by skystebnicki** [comment]
Awesome. Thank you!

**Pull request merged**
