### PR TITLE
Fixed wrong clone error message

### PR DESCRIPTION
**Pull request by luizdepra**
After cloning successfully, vagrant-git was printing error message about clone failure.

    Cloning into 'folder/project'...
    remote: Counting objects: 3, done.
    remote: Total 3 (delta 0), reused 0 (delta 0)
    Receiving objects: 100% (3/3), done.
    Checking connectivity... done.
    ==> default: Failed to clone git@some.address.com:web/project.git into folder/project
    ==> default: WARNING: Encountered errors when cloning repos.
    ==> default: -- folder/project --
    ==> default: Failed to clone git@some.address.com:web/project.git into folder/project
    ==> default: If these were due to transient network issues, try again with:
    ==> default:    vagrant halt
    ==> default:    vagrant up

The problem was a missing `elsif` in the clone action code.

### CODE REVIEW

**Comment by alangarf** [comment]
Nice! Thanks for the PR.

**Comment by luizdepra** [comment]
@alangarf, can you do a release of this PR?
`vagrant plugin add` is downloading an old version (v0.1.4).

**Comment by alangarf** [comment]
Ahh yep sorry.

**Comment by alangarf** [comment]
Done. Sorry for the delay.

**Comment by luizdepra** [comment]
ty :-1:

**Pull request merged**
